
jobs:
  include:
  - os: linux
    dist: bionic
    name: Linux (Ubuntu 18.04) E+ Tests
    language: python
    python: 3.6
    before_script: pip3 install -r requirements.txt
    script: python3 setup.py run --run-config ubuntu1804
  - os: linux
    dist: focal
    name: Linux (Ubuntu 20.04) E+ Tests
    language: python
    python: 3.6
    before_script: pip3 install -r requirements.txt
    script: python3 setup.py run --run-config ubuntu2004
#  - os: osx
#    name: Mac 10.14 E+ Tests
#    osx_image: xcode11.3
#    before_script: pip3 install -r requirements.txt
#    script: python3 setup.py run --run-config mac1014
  - os: osx
    name: Mac 10.15 E+ Tests
    osx_image: xcode11.4
    before_script: pip3 install -r requirements.txt
    script: python3 setup.py run --run-config mac1015
  - os: windows
    language: cpp
    name: Windows 32-bit E+ Tests
    before_script:
      - choco install python --version 3.6.8
      - pip3 install -r requirements.txt
    script: python setup.py run --run-config win32
    env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
  - os: windows
    language: cpp
    name: Windows 64-bit E+ Tests
    before_script:
      - choco install python --version 3.6.8
      - pip3 install -r requirements.txt
    script: python setup.py run --run-config win64
    env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
  - os: linux
    dist: bionic
    name: Flake8
    language: python
    python: 3.6
    before_script: pip3 install -r requirements.txt
    script: python3 setup.py flake8
